### PR TITLE
321 traffic signal monitor date fix

### LINKED ISSUE #321: Traffic Signal Monitor showing "NaN"
On the Traffic Signal Monitor, "Status Date" and "Duration" are displaying as "NaN." Cause appears to be multiplying a date by 1000, resulting in NaN. Removing this operation seems to fix the problem, but I want to verify the output is correct before making the change.

### PR DESCRIPTION
**Pull request by tcwcodes**
Fixes #321 

Note: I started this branch with the code from [this existing pull request](https://github.com/cityofaustin/transportation.austintexas.io/pull/320), so it includes all those updates as well.

### CODE REVIEW

File: components/js/signal-projects.js [hunk 1]
```diff
@@ -413,7 +413,13 @@ function createMarkers(data, style) {
         var lat = data[i].location_latitude;
         
         var lon = data[i].location_longitude;
-         
+        
+        if (data[i].construction_note_date) {
+            console.log(data[i], formats.formatDate( new Date(data[i].construction_note_date) ));
+        } else {
+            console.log(data[i], "no date");
+        };
```
Comment (mateoclarke) [inline components/js/signal-projects.js]: Can we remove all of the `console.log`s before you merge?

Comment (mateoclarke) [reply components/js/signal-projects.js]: understand it helps with debugging and testing but we shouldn't leave it in there because it'll make debugging more tricky in the future.

Comment (tcwcodes) [reply components/js/signal-projects.js]: Totally understand - I generally remove my debugging/testing code but I missed that one. Sorry about that, will make sure to get rid of it before I merge!
